name: ${project.name}
main: org.dequis.tenjava.Derp
version: ${project.version}
author: dx
description: "what is this i don't even"

commands:
   derp:
      description: herp a derp
      usage: /<command>
